### ISSUE TITLE
Free/premium bug

### ISSUE THREAD

**Issue by deXxterlab97** [CSMarkBenchmark/CSMarkCoreCLI#8]
Link of the problem: https://www.youtube.com/watch?v=nyph-gxIKbs&feature=youtu.be

Description: as you can see in the video, it would show Free and Premium at start randomly, despite me clearly owning Premium. It has no pattern, so you don't know if it would show Premium or Free when the program is launched.

Internet is connected. Can provide another video with me pinging to MS store or other site while running the program in case. 

Ignore the update bug popup, it's been fixed.

Contact me on discord or here if need more info.

**Comment by AluminiumTech** [comment]
CSMarkCore does not feature premium and is 100% free. Please open an in issue in the CSMarkDesktop repo.
